import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card';import { Button } from '@/components/ui/button';import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';import { CandlestickChart } from '@/components/charts/CandlestickChart';import { PercentageBadge } from '@/components/shared/PercentageBadge';import { TokenAvatar } from '@/components/shared/TokenAvatar';import { TokenRow } from '@/components/shared/TokenRow';import { formatUsd } from '@/lib/format';import { asks,bids,detailCandles,trades } from '@/lib/mock/details';import { tokens } from '@/lib/mock/tokens';import type { Token } from '@/types';
export function TokenHero({token}:{token:Token}){const metrics=[['ارزش بازار',token.marketCap],['حجم ۲۴ساعت',token.volume],['عرضه در گردش',token.supply],['بالاترین/پایین‌ترین','۱۰۶K / ۱۰۱K']];return <Card><CardContent className="pt-5"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-4"><TokenAvatar symbol={token.symbol} color={token.color} className="size-16 text-2xl"/><div><h1 className="text-3xl font-black">{token.persianName} <span className="text-[#9CA3AF]">{token.symbol}</span></h1><div className="mt-2 flex items-center gap-3"><span className="text-4xl font-black">{formatUsd(token.price)}</span><PercentageBadge value={token.change24h}/></div></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([k,v])=><div key={k} className="rounded-2xl border border-[#262B36] bg-[#0F1117] p-4"><p className="text-xs text-[#9CA3AF]">{k}</p><p className="mt-2 font-bold">{v}</p></div>)}</div></div></CardContent></Card>}
export function DetailChart(){return <Card className="xl:col-span-2"><CardHeader className="flex-row items-center justify-between"><CardTitle>نمودار قیمت</CardTitle><div className="flex flex-wrap gap-2">{['1H','24H','7D','1M','3M','1Y'].map(t=><Button key={t} variant="ghost" className="rounded-xl border border-[#262B36] text-[#9CA3AF]">{t}</Button>)}</div></CardHeader><CardContent><div className="h-[420px]"><CandlestickChart data={detailCandles} height={360}/></div></CardContent></Card>}
export function SideInfo({symbol}:{symbol:string}){return <div className="space-y-6"><Card><CardHeader><CardTitle>ارزهای مشابه</CardTitle></CardHeader><CardContent className="space-y-2">{tokens.filter(t=>t.symbol!==symbol).slice(0,4).map(t=><TokenRow key={t.symbol} token={t}/>)}</CardContent></Card><Card><CardHeader><CardTitle>معاملات اخیر</CardTitle></CardHeader><CardContent><SmallTrades/></CardContent></Card></div>}
function SmallTrades(){return <Table><TableHeader><TableRow><TableHead>قیمت</TableHead><TableHead>مقدار</TableHead><TableHead>زمان</TableHead></TableRow></TableHeader><TableBody>{trades.slice(0,5).map((tr,i)=><TableRow key={i}><TableCell className={tr.type==='buy'?'text-[#6EEB83]':'text-[#FF5B5B]'}>{formatUsd(tr.price)}</TableCell><TableCell>{tr.amount}</TableCell><TableCell>{tr.time}</TableCell></TableRow>)}</TableBody></Table>}
export function StatCards(){return <section className="grid gap-4 md:grid-cols-4">{[['ATH','۱۲۲٬۰۰۰ دلار'],['ATL','۳٬۱۵۶ دلار'],['رتبه بازار','#۱'],['نقدشوندگی','بسیار بالا']].map(([k,v])=><Card key={k}><CardContent className="pt-5"><p className="text-sm text-[#9CA3AF]">{k}</p><p className="mt-2 text-2xl font-black">{v}</p></CardContent></Card>)}</section>}
export function OrderBook(){return <Card><CardHeader><CardTitle>دفتر سفارش</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><OrderTable title="خرید" rows={bids} color="#6EEB83"/><OrderTable title="فروش" rows={asks} color="#FF5B5B"/></CardContent></Card>}
function OrderTable({title,rows,color}:{title:string;rows:typeof bids;color:string}){return <div><h3 className="mb-2 font-bold" style={{color}}>{title}</h3><div className="space-y-1">{rows.map(r=><div key={r.price} className="relative grid grid-cols-3 overflow-hidden rounded-lg bg-[#0F1117] px-3 py-2 text-sm"><span className="absolute inset-y-0 left-0 opacity-10" style={{backgroundColor:color,width:`${r.total}%`}}/><span className="relative">{formatUsd(r.price)}</span><span className="relative text-center">{r.amount}</span><span className="relative text-left">{r.total}%</span></div>)}</div></div>}
export function TradeHistory(){return <Card><CardHeader><CardTitle>تاریخچه معاملات</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>قیمت</TableHead><TableHead>مقدار</TableHead><TableHead>زمان</TableHead><TableHead>نوع</TableHead></TableRow></TableHeader><TableBody>{trades.map((tr,i)=><TableRow key={i}><TableCell className={tr.type==='buy'?'text-[#6EEB83]':'text-[#FF5B5B]'}>{formatUsd(tr.price)}</TableCell><TableCell>{tr.amount}</TableCell><TableCell>{tr.time}</TableCell><TableCell>{tr.type==='buy'?'خرید':'فروش'}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}
